spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio-picpay
    username: postgres
    password: henrique123
    driverClassName: org.postgresql.Driver
    baseline-on-migrate: true
    jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
    ddl-auto: create-drop

  flyway:
    enabled: true
    locations: classpath:db/migration
security:
  jwt:
    secret: 0412c946-a382-4be6-9245-ebde9ef911dd
    expiration: 900